apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-6jzx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app-2/devfile-sample-python-basic-6jzx@sha256:e14d1f3dc0563a192f03d3e4a2ebbda47cb59a9d9b0d02080dd44d412d53b209
        name: my-python
        resources: {}
status: {}
